Portfolio merge
Thinus01/Portfolio_Part_2 pull request #1
Opened 2022-10-29 12:52 UTC by Thinus01

Updated HTML & CSS with middle part and about me
Added Linters
Added README

2022-10-29 14:28 UTC, Debas-31 requested changes
## Hi @Thinus01  :wave:
# Status: Required Change :recycle:
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media2.giphy.com/media/WTdg5GBR45X6NbxqJK/giphy.gif"/>

## Highlights
- Linters setup :heavy_check_mark:
- GitHub flow :heavy_check_mark: 
- Commit message :heavy_check_mark:  
 
## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-29 14:28 UTC, Debas-31 commented on index.html
> +                    <li><a id="langicon" href="#"><img src="images/css.svg" alt="css"></a></li>
[ ] Great at implementing the about-myself section design, but some issues to figure out in your design. As much as possible, stick to the Figma template you choose. Make sure of the alignment of the section, like the CSS property margin and padding as the designed template.

| Figma template design  | Your design|
| ------------- | ------------- |
|![Screenshot from 2022-10-29 16-42-58](https://user-images.githubusercontent.com/65129228/198836502-1a3f025c-3443-4b16-9627-8a0d7ce78949.png)| ![Screenshot from 2022-10-29 16-47-10](https://user-images.githubusercontent.com/65129228/198836526-a194957a-77ef-4c67-b76c-5d47678e4732.png)|

2022-10-29 14:28 UTC, Debas-31 commented on index.html
> +        </section>
- [ ] Please note that all your cards should be in one section. You have used so many sections in a section that it's better to use your cards, which can be articles in a section or just divs in a section. Also, you are to align the contents of the section (that is, the cards) using a CSS grid as demanded by project requirements. Kindly fix this, please.

2022-10-29 14:28 UTC, Debas-31 commented on index.html
> +                    <section id="frame2">
- [ ] Please note that you should have only one h1 in the whole of your document; kindly change this to any other heading tag(from h2 to h5). It is SEO best practice. Kindly check [here](https://yoast.com/one-h1-heading-per-post/) for more information.

2022-10-29 14:28 UTC, Debas-31 commented on index.html
> +                    <section id="frame2">
- [ ] Please note that you should have only one h1 in the whole of your document; kindly change this to any other heading tag(from h2 to h5). It is SEO best practice. Kindly check [here](https://yoast.com/one-h1-heading-per-post/) for more information.

2022-10-29 14:28 UTC, Debas-31 commented on index.html
> +                    <p id="project_title">Multi-Post Stories</p>
- [ ] Please note that you should have only one h1 in the whole of your document; kindly change this to any other heading tag(from h2 to h5). It is SEO best practice. Kindly check [here](https://yoast.com/one-h1-heading-per-post/) for more information.

2022-10-29 14:28 UTC, Debas-31 commented on index.html
> +                    <section id="frame2">
- [ ] Please note that you should have only one h1 in the whole of your document; kindly change this to any other heading tag(from h2 to h5). It is SEO best practice. Kindly check [here](https://yoast.com/one-h1-heading-per-post/) for more information.

2022-10-29 18:10 UTC, OyePriscilla requested changes
Hi @Thinus01 😄 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![so-close-so-close-seth-meyers](https://user-images.githubusercontent.com/103386183/196425724-8ca5825c-b02a-4983-b976-4bd0a2f70f9a.gif)

 ## Highlights
* Linters setup ✔️
* GitHub flow ✔️
* Commit message ✔️

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @oyepriscilla in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-29 18:10 UTC, OyePriscilla commented on index.html
> +                <section id="primary_text">
- [ ] Please kindly effect the changes that the previous reviewer requested. 😄.

> Please note that all your cards should be in one section. You have used so many sections in a section that it's better to use your cards, which can be articles in a section or just divs in a section. Also, you are to align the contents of the section (that is, the cards) using a CSS grid as demanded by project requirements. Kindly fix this, please.

2022-10-29 18:10 UTC, OyePriscilla commented on index.html
> +                    <p id="project_title">Tonic</p>
- [ ] You've not implemented this as well for all the project titles. Be encouraged, you can do this. 👍 You can change the `p `tag to `h3 `tag. 😄 

> Please note that you should have only one h1 in the whole of your document; kindly change this to any other heading tag(from h2 to h5). It is SEO best practice. Kindly check [here](https://yoast.com/one-h1-heading-per-post/) for more information.

2022-10-29 18:10 UTC, OyePriscilla commented on index.html
> +                    <li><a id="langicon" href="#"><img src="images/css.svg" alt="css"></a></li>
- [ ] Kindly make a little adjustment here as well. 👍 

## Your design

![crr22](https://user-images.githubusercontent.com/103386183/198846449-27dfb07b-1f96-4244-88ef-db75717b51ba.png)


## Figma design 

![crr24](https://user-images.githubusercontent.com/103386183/198846468-2846fb90-9f41-4044-94f5-c0579a8bf5e7.png)

2022-10-29 19:57 UTC, OyePriscilla requested changes
# Hi @Thinus01 👋
## Status: Required Change ♻️

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f5754646735474252343558364e6278714a4b2f67697068792e676966](https://user-images.githubusercontent.com/103386183/198850331-fcaafea0-06f3-4a40-8ea6-623ab4ee70f9.gif)

## Highlights
Linters setup ✔️
GitHub flow ✔️
Commit message ✔️

## Required Changes ♻️

Check the comments under the review.

Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-10-29 19:57 UTC, OyePriscilla commented on index.html
> +                </section>
- [ ] According to best practices, you can only use `section` tag to group related elements. The format below might be helpful for you.

<section>
                <div>
                    <img src="resources/img/SnapshootPortfolio.png" alt="snapshoot">
                </div>
                <div>
                    <div>
                        <h1 class="tonic">Tonic</h1>
                        <ul>
                            <li><a href="#">CANOPY</a></li>
                            <li><a href="#">Back End Dev</a></li>
                            <li><a href="#">2015</a></li>
                        </ul>
                    </div>
                    <p>Proof read my works here, no account sign-ups required</p>
                    <ul>
                        <li>html</li>
                        <li>css</li>
                        <li>javascript</li>
                    </ul>

2022-10-29 20:55 UTC, Lameck1 reviewed
Hello @Thinus01 👋,

_This is an additional review as a result of the second opinion request._

The concerns the reviewer has raised are genuine. It's not just a matter of best practices, it is about using HTML tags for what they are meant. The reviewer has explained the concerns and why the change is necessary and has even given you an example to work with. You cannot use the `<section>` tag to create a list, we have the `<ul>` or the `<ul>` for that. You cannot also use the `<section>` tag to wrap every HTML with it.

Every HTML tag has meaning and this meaning is interpreted by our web browser to lay out the information properly. We should strive to use semantic HTML. It is also the work of the Code Reviewers to check whether we are writing semantic HTML. Please, don't hold against @OyePriscilla for giving you valuable feedback, that is what is expected of the Code Reviewers.

Would it make you happy if your projects were approved with gross mistakes? Have you thought about how that will affect your chances of getting a job? If we don't get exposed to the right way of doing things in the code review process, how can we learn?

Please work on the required changes and submit them for another review. Consider working with the example that you've been provided in the last review.

Keep rocking 🚀!

2022-10-31 10:01 UTC, ichala requested changes
Hi @Thinus01 
Good job so far! 
👏👏👏 
There are some issues that you still need to work on to go to the next project but you're almost there!

![the-simpsons-homer-simpson](https://user-images.githubusercontent.com/28307960/157369993-50d5ba12-099f-4f2a-9a19-5e57ee2d1c96.gif)

## To Highlight 🎉

- Removed sections tags✔️ 
 
 ## Required Changes ♻️

- [ ] 🛑 **_Check The comments below_**

## Optional suggestions

- N/A

**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-31 10:01 UTC, ichala commented on index.html
> +                </div>
- [ ] Great job removing the sections tags from the lists 👏  , but as mentioned by both  the previous reviewer and the Sr Reviewer, we should be semantically correct and use the tags `<ul>` & `<li>` for lists, here's a hint on how to do it : 

❌ Incorrect : 
```HTML
       <div id="frame2">
                        <div id="client">
                            <h2 id="pcanopy">CANOPY</h2>
                        </div>
                        <img id="counter">
                        <div id="role">
                            <h3 id="pcareer">Back End Dev</h3>
                        </div>
                        <img id="counter">
                        <div id="year_label">
                            <h5 id="pcareer">2015</h5>
                        </div>
             </div>
```

✔️  Correct : 

```HTML
       <ul id="frame2">
                        <li id="client">
                            <h2 id="pcanopy">CANOPY</h2>
                        </li>
                        <li id="role">
                            <img id="counter">
                            <h3 id="pcareer">Back End Dev</h3>
                        </li>
                        <li id="year_label">
                            <img id="counter">
                            <h5 id="pcareer">2015</h5>
                        </li>
          </ul>
```

  _**🛑 Kindly fix it for all of your cards 🙏**_

2022-10-31 12:27 UTC, fherrerao approved these changes
# ✅  🎆  STATUS APPROVED! ✅ 🎆 
#
Hi @Thinus01, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Great Job Yes GIF by Hollywood Suite](https://user-images.githubusercontent.com/91301423/197768588-bd30fde7-65cc-4249-9dd9-cc1fc1889a94.gif)


## Highlights
✔️  No linter errors.
✔️  You used the correct GitHub-Flow.
✔️  Good README
✔️  Good Commit Messages

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-31 12:30 UTC, merged